### ISSUE TITLE
Open by news index and add an URL opener 

### ISSUE THREAD

**Issue by movalex** [ozio/meduza#6]
1) Хорошо бы каждой статьи добавить индекс, как в rainbowstream. 
Например: 

> > > 19:52 НОВОСТИ __ 002___
> > > Йозеф Блаттер объявил об отставке
> > > meduza 002 (или open 002)
> > > Йозеф Блаттер объявил об отставке
> > > 2 июня 2015 г., 19:52, источник: The Guardian (...)

2) Возможно ли добавить url-парсер с возможностью открывать линки в дефолтном браузере, используя такой regexp, например?

```
^(?:(\w+):\/\/)?(?:([^:\n\r]+):([^@\n\r]+)@)?(?:([^:\/\n\r]+)(?::(\d+))?)(\/?[^?#\n\r]+)?\??([^#\n\r]*)?\#?([^\n\r]*)?$
```

3) стриминг новостей не прошу, но надеюсь :)

**Comment by ozio** [comment]
1. А чем плох выбор по времени?
2. Не понимаю, ты хочешь чтобы была команда вроде meduza open 13:52, которая бы открывала новость в браузере? Я знаю как это делается на OS X, но сомневаюсь, что это будет работать везде. Или ты знаешь какой-то универсальный способ?
3. Постараюсь.

Спасибо за предложения!

**Comment by movalex** [comment]
1) это только из соображений скорости восприятия - простой порядковый номер запомнить легче, чем ассоциировать время с тем, что оно не только время публикации, но и порядковый номер поста, который нужно использовать, чтобы просмотреть текст статьи, причем еще и вбивать несчастное двоеточие. 
2) Если пользовался rainbowstream https://github.com/DTVD/rainbowstream,  то наверняка обратил внимание, что ссылки там парсятся прямо в окне терминала. Можно нажать правой кнопкой на ссылке и выбрать Open URL, а можно дать команду open (№), и тогда  она откроется во внешнем браузере. Как-то так. 
3) супер)

Kind regards,
Alexey Bogomolov

**Comment by ozio** [comment]
1. У меня в планах сделать таким ID минута выпуска статьи. 2 цифры всего и пересечения не такие частые.
2. Нажал правой кнопкой по ссылке в iTerm (OS X) http://oz.dropmark.com/237265/4911527, ты уверен, что там есть какой-то механизм превращения ссылки в ссылку? Возможно, если добавить http:// к началу ссылки, то получится, но я так сделал из-за краткости.

**Comment by ozio** [comment]
2) Добавил https:// к каждой ссылке и вынес ссылки вниз как сноску, чтобы не рвало контент.

**Comment by iamstarkov** [comment]
в iTerm вы можете открывать ссылки кликая на них с зажатым cmd
