### ISSUE TITLE
Просмотр новостей не текущего дня

### ISSUE THREAD

**Issue by fotonmoton** [ozio/meduza#7]
Если попытаться посмотреть статью за прошлый (или отличный от текущего) день, то, собственно, статью эту не посмотреть. Я тоже за то, чтобы давать каждому топику порядковый номер.
С уважением, Григорий.
![1](https://cloud.githubusercontent.com/assets/7763084/7985682/15043846-0adb-11e5-88ce-13deae25b06e.png)

**Comment by fotonmoton** [comment]
Уже разобрался, нужно было указывать и тип статьи: meduza shapito 19:16.

**Comment by ozio** [comment]
Можешь ещё добавить --number 30 или -n 30 (это максимум, который позволяет Медуза). А так время и есть оптимальный id для статьи. От того, что появится 1, 2, 3, 4 принципиально ничего не поменяется. Уникальные идентификаторы появятся, если будет стрим новостей.

**Comment by gsamat** [comment]
Что значит стрим новостей?

**Comment by ozio** [comment]
Запускаешь приложение и оно не закрывается, а остаётся работать и показывать новости по мере их появления.

**Comment by gsamat** [comment]
У нас пушей таких пока нет у самих, но можно спрашивать раз в минуту, как
мы собственно сами и делаем.

**Comment by ozio** [comment]
Обещаю, что если сделаю, то оно не будет генерировать по запросу в секунду. Что-нибудь поумнее придумаю.)

**Comment by gsamat** [comment]
Ну можешь сделать свою пушилку, которая раз в минуту ходит к нам, а потом
пушит всем клиентам :)
